### ISSUE TITLE
Thresholds about different baselines

### ISSUE THREAD

**Issue by Fujiaoji** [lindsey98/PhishingBaseline#2]
Hi, sorry to disturb you again. 

I am working on figure 11 of phishintention and could you please share the thresholds you used in different models. For example, the visualphishnet the default threshold is 1.5, but if we want to get the figure 11 we need more thresholds. 

Moreover, in the visualphishnet, when testing the screenshots, it seems not get the embedding, it leads to almost all images have the minimal distance with the same target image. I am wondering if there are some problems. And could you please also share the 9334 target screenshots?
Thanks

From: Fujiao

**Comment by lindsey98** [comment]
Hi Fujiao,
  I have tested thresholds of range(0.87, 1, 0.01) for EMD, range(0.1, 1,
0.1) for Phishzoo, and range(0.1, 2.4, 0.1) for VisualPhishnet.
  I found that the optimal thresholds for each solution are 0.94 for EMD,
0.4 for Phishzoo, and 1 for VisualPhishnet.

Fujiao Ji ***@***.***> 于2023年8月28日周一 02:14写道：

**Comment by Fujiaoji** [comment]
> Hi Fujiao, I have tested thresholds of range(0.87, 1, 0.01) for EMD, range(0.1, 1, 0.1) for Phishzoo, and range(0.1, 2.4, 0.1) for VisualPhishnet. I found that the optimal thresholds for each solution are 0.94 for EMD, 0.4 for Phishzoo, and 1 for VisualPhishnet. Fujiao Ji ***@***.***> 于2023年8月28日周一 02:14写道：
> […](#)

Thanks for your help! Have a great day.
